# Generated by Django 6.0.5 on 2026-05-22 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryPriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_type', models.CharField(max_length=50, unique=True)),
                ('hire_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TyrePriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('PRESSURE', 'Pressure Check'), ('PUNCTURE', 'Puncture Fixing'), ('VALVE', 'Valve Replacement')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BatteryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('battery_type', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('HIRE', 'Hire'), ('SALE', 'Sale')], max_length=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TyreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('tyre_size', models.CharField(max_length=20)),
                ('tyre_model', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('PRESSURE', 'Pressure Check'), ('PUNCTURE', 'Puncture Fixing'), ('VALVE', 'Valve Replacement')], max_length=20)),
                ('service_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('PERSONAL', 'Personal Car'), ('TAXI', 'Taxi'), ('COASTER', 'Coaster'), ('BODA', 'Boda-boda')], max_length=20)),
                ('number_plate', models.CharField(max_length=10, unique=True)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('arrival_datetime', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('nin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_signed_out', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100)),
                ('receipt_number', models.CharField(max_length=50)),
                ('signout_datetime', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nin_number', models.CharField(blank=True, max_length=20)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_status', models.CharField(default='PAID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.vehicle')),
            ],
        ),
    ]
