# Generated by Django 6.0.5 on 2026-05-14 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('parking_revenue', models.IntegerField()),
                ('tyre_revenue', models.IntegerField()),
                ('battery_revenue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Truck', 'Truck'), ('Car', 'Personal Car'), ('Taxi', 'Taxi'), ('Coaster', 'Coaster'), ('Boda', 'Boda-boda')], max_length=20)),
                ('number_plate', models.CharField(max_length=6, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('nin_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'System Admin'), ('Manager', 'Section Manager'), ('Cashier', 'Cashier')], max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TyreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Pressure', 'Pressure'), ('Puncture', 'Puncture Fixing'), ('Valve', 'Valve Replacement')], max_length=20)),
                ('price', models.IntegerField()),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkease.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('signed_out_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkease.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Hire', 'Battery Hire'), ('Sale', 'Battery Sale')], max_length=10)),
                ('price', models.IntegerField()),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkease.vehicle')),
            ],
        ),
    ]
