# Generated by Django 6.0.5 on 2026-05-14 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receiver_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receiver_nin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='signed_out_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
